baseURL = "https://serhii-babich.github.io/"
languageCode = "uk-UA"
title = "Сергій Бабіч"
theme = "winston"
googleAnalytics = "G-MVMXZSTYSD"
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  twitter_handle = "@babichss"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = true
  addDot = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true